### ISSUE TITLE
Curious about methodology for player list

### ISSUE THREAD

**Issue by RalphChahine** [gretzky/nhl-api#2]
Hi Gretzky!

First of all great work, i love what you have done and I have not ran into any issues yet. However, I am quite new with the NHL API and thankfully came accros your work. I was wondering if you could explain to me the methodology you used to write this list of players with their matching ID. With my brief experience with the NHL API I seemed to be only able to retrieve active players ID through their respective teams. How did you manage to get the ID's of non active players? 

Thanks

**Comment by gretzky** [comment]
Hi @RalphChahine! Good question. The NHL API doesn't expose any endpoints for inactive players, however inactive players have player IDs that still exist on the player endpoint. I retrieved every player by crawling the API using player ID number formats.

More in depth explanation: a player ID is 7 digits long. Since all active player IDs start with 84 and 85, I started with every possible combination of 7 digits starting with 84 and 85. After that, I made requests with all possible combinations of 7 digit numbers -- 0000000-9999999. It took awhile, but I'm confident that I was able to scrape every player. I'm pretty shocked they don't cap the number of requests to the API but 🤷‍♀ 

I plan on rescraping a few times a year to account for call-ups, drafts, etc.
